/**
 * code generated by JHelper
 * More info: https://github.com/AlexeyDmitriev/JHelper
 * @author champon
 */

#include <iostream>
#include <fstream>
#include <bits/stdc++.h>
#define se cout << "test ok" << endl;
#define sp << " " <<
#define enl "\n"
using namespace std;
using ll=long long;
using ld=long double;
using vi = vector<int>;
using vii = vector<vector<int>>;
using vl = vector<ll>;
using vll = vector<vector<ll>>;
using vlll = vector<vector<vector<ll>>>;
using vc = vector<char>;
using vcc = vector<vector<char>>;
using pi = pair<int, int>;
using pl = pair<ll, ll>;
ll mod = ll(1e9)+7;
ll inf = ll(1e18);
void bl(bool b, ostream& out=cout){ out << (b ? "Yes" : "No") << endl; }
void bl2(bool b, ostream& out=cout){ out << (b ? "YES" : "NO") << endl; }
template<typename T> inline bool chmax(T &a, T b){ if(a<b){a=b; return true;} return false; }
template<typename T> inline bool chmin(T &a, T b){ if(a>b){a=b; return true;} return false; }
int dx[] = {1, 0, -1, 0, 1, -1, 1, -1};
int dy[] = {0, 1, 0, -1, 1, -1, -1, 1};

#ifndef INCLUDE_DEBUG_HPP
#define INCLUDE_DEBUG_HPP

#include <iostream>
#include <vector>
#include <map>
using namespace std;

namespace dbg {
    using ll = long long;

    class Debug {
    public:
        Debug(){}
        template<typename T>
        void vd(vector<T> vec);
        template<typename T>
        void vd2(vector<vector<T>> vec);
        template<typename T>
        void ad(T *arr, ll n);
        template<typename T, size_t N>
        void ad2(T (&arr)[N], ll n);
        template<typename T>
        void md(T mp);
    };

    template<typename T>
    void Debug::vd(vector<T> vec) {
        for (auto vv : vec) cout << vv << " ";
        cout << endl;
    }

    template<typename T>
    void Debug::vd2(vector<vector<T>> vec) {
        for (auto vv : vec) {
            for (auto vvv : vv) cout << vvv << " ";
            cout << endl;
        }
    }

    template<typename T>
    void Debug::ad(T *arr, ll n) {
        for (int i = 0; i <= n; i++) cout << arr[i] << " ";
        cout << endl;
    }

    template<typename T, size_t N>
    void Debug::ad2(T (&arr)[N], ll n) {
        for (int i = 0; i <= N; i++) for (int j = 0; j <= n; j++) cout << arr[i][j] << " ";
        cout << endl;
    }

    template<typename T>
    void Debug::md(T mp) {
        cout << "key : value" << endl;
        for (auto const &m : mp) cout << m.first << " : " << m.second << endl;
        cout << endl;
    }

}

#endif //INCLUDE_DEBUG_HPP

using dbg::Debug;
Debug debug;

#ifndef DEFINE_DIJKSTRA_HPP
#define DEFINE_DIJKSTRA_HPP


#include <queue>
using namespace std;

namespace dijkstra {

    using ll = long long;
    const ll inf = 1e18;

    class Dijkstra {
    private:
        struct edge {
            int to;
            ll cost;
            edge(int t, ll c) : to(t), cost(c) {}
        };
        typedef pair<ll, int> P;
    public:
        int n;
        vector<edge> g[100010];
        vector<ll> dist;

        Dijkstra(int n) : n(n) {};
        void add(int from, int to, ll cost);
        void build(int s);
        ll result(int s);
    };

    void Dijkstra::add(int from, int to, ll cost) {
        g[from].push_back(edge(to, cost));
    }

    void Dijkstra::build(int s) {
        priority_queue<P, vector<P>, greater<P>> q;
        dist.assign(n, inf);
        dist[s] = 0;
        q.push(P(0, s));
        while (!q.empty()) {
            P p = q.top();
            q.pop();
            int v = p.second;
            if (dist[v] < p.first) continue;
            for (auto const &e : g[v]) {
                if (dist[e.to] > dist[v] + e.cost) {
                    dist[e.to] = dist[v] + e.cost;
                    q.push(P(dist[e.to], e.to));
                }
            }
        }
    }

    ll Dijkstra::result(int s) {
        return dist[s];
    }

}

// verify
// https://atcoder.jp/contests/abc070/tasks/abc070_d

#endif  //DEFINE_DIJKSTRA_HPP
using dijkstra::Dijkstra;

class a {
public:
	void solve(std::istream& in, std::ostream& out) {
	    ll n, e, r;
	    in >> n >> e >> r;

	    ll s, t, d;
	    Dijkstra dij(n);
	    for(int i=0; i<e; i++){
            in >> s >> t >> d;
            dij.add(s, t, d);
//            dij.add(t, s, d);
	    }

	    dij.build(r);
	    for(int i=0; i<n; i++){
	        ll res  = dij.result(i);
	        if(res == inf) out << "INF" << enl;
	        else out << res << enl;
	    }
	}
};


int main() {
    cin.tie(nullptr);
    ios_base::sync_with_stdio(false);
	a solver;
	std::istream& in(std::cin);
	std::ostream& out(std::cout);
	solver.solve(in, out);
	return 0;
}

